/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cbir_kernels_c_PCA */

#ifndef _Included_cbir_kernels_c_PCA
#define _Included_cbir_kernels_c_PCA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbir_kernels_c_PCA
 * Method:    pca
 * Signature: ([FIIII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_cbir_kernels_c_PCA_pca
  (JNIEnv *, jclass, jfloatArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class cbir_kernels_c_SPCA */

#ifndef _Included_cbir_kernels_c_SPCA
#define _Included_cbir_kernels_c_SPCA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbir_kernels_c_SPCA
 * Method:    spca
 * Signature: ([FIIIIIZLjava/lang/String;ZI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_cbir_kernels_c_SPCA_spca
  (JNIEnv *, jclass, jfloatArray, jint, jint, jint, jint, jint, jboolean, jstring, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class cbir_kernels_c_NFindr */

#ifndef _Included_cbir_kernels_c_NFindr
#define _Included_cbir_kernels_c_NFindr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbir_kernels_c_NFindr
 * Method:    nFindr
 * Signature: ([FIIIZLjava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_cbir_kernels_c_NFindr_nFindr
  (JNIEnv *, jclass, jfloatArray, jint, jint, jint, jboolean, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class cbir_kernels_c_LSU */

#ifndef _Included_cbir_kernels_c_LSU
#define _Included_cbir_kernels_c_LSU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbir_kernels_c_LSU
 * Method:    lsu
 * Signature: ([F[IIIIII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_cbir_kernels_c_LSU_lsu
  (JNIEnv *, jclass, jfloatArray, jintArray, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
