/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cbir_kernels_cuda_CudaKernel */

#ifndef _Included_cbir_kernels_cuda_CudaKernel
#define _Included_cbir_kernels_cuda_CudaKernel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbir_kernels_cuda_CudaKernel
 * Method:    initCuda
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbir_kernels_cuda_CudaKernel_initCuda
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class cbir_kernels_cuda_SPCA */

#ifndef _Included_cbir_kernels_cuda_SPCA
#define _Included_cbir_kernels_cuda_SPCA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbir_kernels_cuda_SPCA
 * Method:    spca
 * Signature: ([FIIIIIZLjava/lang/String;ZI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_cbir_kernels_cuda_SPCA_spca
  (JNIEnv *, jclass, jfloatArray, jint, jint, jint, jint, jint, jboolean, jstring, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class cbir_kernels_cuda_NFindr */

#ifndef _Included_cbir_kernels_cuda_NFindr
#define _Included_cbir_kernels_cuda_NFindr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbir_kernels_cuda_NFindr
 * Method:    nFindr
 * Signature: ([FIIIZLjava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_cbir_kernels_cuda_NFindr_nFindr
  (JNIEnv *, jclass, jfloatArray, jint, jint, jint, jboolean, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class cbir_kernels_cuda_LSU */

#ifndef _Included_cbir_kernels_cuda_LSU
#define _Included_cbir_kernels_cuda_LSU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cbir_kernels_cuda_LSU
 * Method:    lsu
 * Signature: ([F[IIIIII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_cbir_kernels_cuda_LSU_lsu
  (JNIEnv *, jclass, jfloatArray, jintArray, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
